### ISSUE TITLE
Please contact me back

### ISSUE THREAD

**Issue by tdimeco** [craftedBits/hello-world#2]
Hello Roger,

Unfortunately I am unable to send a private message to you on GitHub, would you mind to contact me at <hidden> to start the conversation? I have something to ask you for. Do not worry, It is not spam or phishing! 😊

Thank you, and have a good day!

Thomas

**Comment by craftedBits** [comment]
Thomas,
1. I don't know you. 
2. If you had a question, you could have asked it already. 
3. Your message above looks exactly like spam or phishing.  
4. I suspect you are a bad actor and are up to no good. 
5 Stop spamming me.

**Comment by tdimeco** [comment]
Thank you for your lovely reply Roger.
Have a good day!

**Comment by craftedBits** [comment]
OK.. What is it.. What do you want to ask me for?  It definitely sounds like you want me to do something for you.  Man up and say outright what it is.  Don't be a weasel.  

By not asking me your question directly, You fit profile of a spammer perfectly.  
Be a man,  ask your f...ing question. 

Your approach.. looks like a sneaky way of getting people to start a conversation w/ you.  ie: You offer zero information about yourself.. and expect people give just up their private emails, and start a conversation w/ Mr total mystery spammer.  Only a complete idiot would respond to that.  What the fuck do you want?  Are you trying to sell us something?  

--RW

**Comment by tdimeco** [comment]
Thank you Roger. Sorry about the message, you are actually right, I should have asked my question publicly, directly in the issue. I didn't want for privacy reasons (and because we can not send private messages on GitHub). But well, it's not important now...

I am, with @hnic0las, the cofounder of the CraftedBits company, a small tech company based in France (public website: https://www.craftedbits.io). It would be nice for us to own the `craftedbits` username on GitHub. I would like to ask you if you are open to change your GitHub username. I call on your kindness, as this will be very helpful for us. I am available for discussing, here in the issue, if needed.

Good day.

Thomas

**Comment by craftedBits** [comment]
I am definitely NOT interested in changing my GitHub username.  I like my "craftedBits" GitHub username.  I would NEVER consider changing it.  

Your original GitHup message to me was deceptive non-reciprocal, and spammy.  Thanks for proving all my suspicions, cited above, were spot-on.
     1. I don't know you.
     2. If you had a question, you could have asked it in the 1st message.
     3. Your message above looked exactly like spam or phishing. 
     4. I suspected you to be a bad actor and up to no good.

Please know this --> Your mother was right!  Always be honest.  Don't try to trick people into doing stuff for you.  Tell the truth, the first time.  Don't try to hide the truth of what you are trying to pull off, behind a veil of privacy.  Personal character is important. 

GitHub is a public forum.  People will figure it all out anyway.  

--RW

**Comment by tdimeco** [comment]
Haha, ok, nervermind.
Bye Roger
